targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "lib/data/network/swagger/"
          output_folder: "lib/data/network/swagger/generated/"
          separate_models: true
          use_path_for_request_names: true
          generate_for_json_converter: true
          include_new_and_empty_list_methods: false
